config/routes.rb
Rails.application.routes.draw do
  # root to: 'home#index'
  root to: 'posts#index'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                 registrations: 'registrations' }

  get '/users/:id', to: 'users#show', as: 'user'
  get '/users', to: redirect("/users/sign_up")

  get '/posts', to: 'posts#search_result', as: 'search_result'

  resources :posts, only: %i(new create index show destroy) do
    resources :photos, only: %i(create)
    resources :comments, only: %i(create destroy)
    resources :likes, only: %i(create destroy)
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post

  validates :image, presence: true

  mount_uploader :image, ImageUploader
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy

  accepts_nested_attributes_for :photos

  def liked_by(current_user)
    Like.find_by(user_id: current_user.id)
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable

  validates :name, presence: true, length: { maximum: 50 }

  def self.find_facebook_user(auth)
    user = User.find_by(uid: auth.id, provider: auth.provider)

    unless user
      user = User.create(
        uid: auth.id,
        provider: auth.provider,
        email: auth.info.email,
        password: Devise.friendly_token[0, 20],
        name: auth.info.name,
        image: auth.info.image
      )
    end

    return user
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def self.get_provider(id)
    user = self.find_by(id: id)
    return user.provider
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :get_name_params, if: :devise_controller?
  before_action :set_search

  def set_search
    @search = Post.includes(:photos, :user).order('created_at DESC').ransack(params[:q])
    @search_articles = @search.result
    # raise
  end

  protected

  def get_name_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    @post = @comment.post
    if @comment.save
      respond_to :js
    else
      flash[:alert] = "コメントに失敗しました"
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = "コメントの削除に失敗しました"
    end
  end
    
  private
    def comment_params
      params.required(:comment).permit(:user_id, :post_id, :comment)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end

  private

  def like_params
    params.permit(:post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :destroy]

  def index
    # @posts = Post.limit(10).order('created_at DESC')
    @posts = Post.includes(:photos, :user).order('created_at DESC')
  end

  def search_result
    if @search_articles.present?
      @posts = @search_articles
      flash.now[:notice] = "#{@posts.size}件ヒットしました。"
      render 'index'
    else
      @posts = @search_articles
      flash.now[:alert] = "検索結果はありません。"
      render 'index'
    end
  end

  def show
  end


  def new
    @post = Post.new
    @post.photos.build
  end

  def create
    @post = Post.new(post_params)
    if @post.photos.present?
      @post.save
      redirect_to root_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to root_path
      flash[:alert] = "投稿に失敗しました"
    end
  end

  def destroy
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:caption, photos_attributes: [:image]).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_facebook_user(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user)
    return user.image if user.image.present?
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end

  def full_title(page_title = '')
    base_title = "Instagram-clone"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.js.erb
$('#comment-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/comment_list", { post: @post } %>');
$('#comment-form-post-<%= @post.id.to_s %> #comment_comment').val("");

$('#comment-post-modal-<%= @post.id.to_s %>').
  html('<%= j render "posts/comment_list", { post: @post } %>');
$('#comment-form-post-modal-<%= @post.id.to_s %> #comment_comment').val("");

app/views/comments/destroy.js.erb
$('#comment-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/comment_list", { post: @post } %>');

$('#comment-post-modal-<%= @post.id.to_s %>').
  html('<%= j render "posts/comment_list", { post: @post } %>');

app/views/layouts/_footer.html.erb
<footer>

  <%= link_to(new_post_path, style: "display:block; width:40px; margin:0 auto; margin-top:1%;") do %>
    <div class="new-post-icon"></div>
  <% end %>

</footer>

app/views/layouts/_head.html.erb
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<%= link_to image_tag("https://fontmeme.com/permalink/190421/6d63b1b1eeebbfd2011a7024a34c39e2.png", class: "insta-header-img nav-link active"), root_path %>

<div style="float:left; margin:10px 0 0 150px; width:50%;">
<%= search_form_for @search, url: search_result_path, class: "form-inline my-2 my-lg-0" do |f| %>
<%= f.search_field :caption_cont ,placeholder: 'キーワード',class:"form-control mr-sm-2" %>
<%= f.submit ("検索") , class: 'btn btn-outline-success my-2 my-sm-0'%></dd>
<% end %>
</div>

<ul class="nav" style="margin-top:15px; float:right;">

  <li class="nav-item">
    <%= link_to "", user_path(current_user), class: "nav-link mypage-icon" %>
  </li>


  <li class="nav-item">
    <%= link_to "", destroy_user_session_path,data: {confirm: "ログアウトしますか？"}, method: :delete, class: "nav-link logout-img" %>
  </li>
</ul>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= render 'layouts/shim' %>
    <%= render 'layouts/head' %>

  </head>

  <body>

    <%  if current_user  %>
    <div id="header-part">
      <%= render 'layouts/header' %>
    </div>
    <% end %>

    <div class="container" style="padding:5%;">

    <% if flash[:notice] %>
      <div class="alert alert-success devise-alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger devise-alert">
        <%= flash[:alert] %>
      </div>
    <% end %>


    <%= yield %>
    </div>
    <%= render 'layouts/footer' if current_user %>
  </body>
</html>

app/views/likes/create.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "いいね", post_like_path(@post.id, @like), method: :DELETE, remote: true, class: "loved hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/like_text", { likes: @post.likes } %>');

app/views/likes/destroy.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "いいねを取り消す", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/like_text", { likes: @post.likes } %>');

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <span><%= comment.comment %></span>
  </div>
<% end %>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.name %>
    <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/posts/_show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modeal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="card mb-3" style="max-width: 540px;">
        <div class="row no-gutters">
          <div class="col-md-8">
            <%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top" %>
          </div>
          <div class="col-md-4">
            <div class="card-body">
              <span>posted by <strong><%= @post.user.name %></strong></span>
              <span><%= @post.caption %></span>
              <div id="comment-post-modal-<%= @post.id.to_s %>">
                <%= render 'comment_list', post: @post %>
              </div>
              <p class="light-color post-time no-text-decoration"><%= time_ago_in_words(@post.created_at).upcase + "前" %></p>
              <hr>
                <div class="row parts" id="comment-form-post-modal-<%= @post.id.to_s %>">
                  <%= form_with model: [@post, Comment.new],  class: "w-100" do |f| %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <%= f.hidden_field :post_id, value: @post.id %>
                    <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
                  <% end %>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% provide(:title, 'home') %>

<% @posts.each do |post| %>
  <div class="col-md-8 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
        <%= image_tag avatar_url(post.user), class: "post-profile-icon" %>
        <p><%= post.user.name %></p>

          <% if post.user_id == current_user.id %>
            <%= link_to "", post_path(post), method: :delete, data: {confirm: '削除しますか？'}, class: "ml-auto mx-0 my-auto delete-post" %>
          <% end %>
        </div>

        <%= link_to post_path(post), remote: true do %>
          <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top", "data-toggle": "modal" , "data-target": "#exampleModalLong"%>
        <% end %>

        <!--modal window-->
        <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true"></div>
        <!--modal window-->

        <div class="card-body">
          <div class="row parts">
            <div id="like-icon-post-<%= post.id.to_s %>">
            <% if post.liked_by(current_user).present? %>
              <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
            <% else %>
              <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
            <% end %>
            </div>

            <div id="like-icon-post-<%= post.id.to_s %>"></div>
          </div>

          <div id="like-text-post-<%= post.id.to_s %>">
            <%= render "like_text", { likes: post.likes } %>
          </div>

          <div>
            <span>posted by <strong><%= post.user.name %></strong></span>
            <span><%= post.caption %></span>
            <div id="comment-post-<%= post.id.to_s %>">
              <%= render 'comment_list', { post: post } %>
            </div>
            <p class="light-color post-time no-text-decoration"><%= time_ago_in_words(post.created_at).upcase + "前" %></p>
            <hr>
            <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
              <%= form_with model: [post, Comment.new], class: "w-100" do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :post_id, value: post.id %>
                <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<% provide(:title, 'post photo') %>

<div class="card text-center" style="margin-top:10%;">
  <div class="card-body">

  <%= form_with model: @post do |f| %>
  <div class="form-group">
    <%= f.text_field :caption, placeholder: "何かコメントしよう" %>
  </div>

  <div class="form-group">
    <%= f.fields_for :photos do |i| %>
      <%= i.file_field :image %>
    <% end %>
  </div>

  <%= f.submit "投稿", class: "btn btn-primary" %>
  <% end %>
  
  </div>
</div>

app/views/posts/show.js.erb
$('#exampleModalLong').html("<%= j(render partial: 'posts/show')  %>");
// $('#exampleModalLong').html("<%= j(render 'posts/show', post: @post)  %>");

$('#exampleModalLong').modal("show");

app/views/users/show.html.erb
<% provide(:title, 'profile') %>

<div class="card">
  <div class="card-body">
    <div id="profile-img-box">
      <%= image_tag avatar_url(@user), class: "round-img" %>
    </div>
    <div id="profile-txt-box">
      <h2><%= @user.name %></h2>
      <%= @user.email %>
    </div>
    <div id="profile-btn-box">
      <% if @user == current_user %>
        <%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
      <% end %>
    </div>
  </div>
</div>